
BOARD_TAG      = userspace

USERSPACE_MAKE = TRUE

ALTERNATE_CORE_PATH = /home/parav/beaglebone/meanbot/Energia/hardware/userspace
ARDUINO_CORE_PATH   = /home/parav/beaglebone/meanbot/Energia/hardware/userspace/cores/virtual
ARDUINO_DIR         = /home/parav/beaglebone/meanbot/Energia
ARDMK_DIR           = /home/parav/beaglebone/meanbot/Arduino-Makefile
ARM_TOOLS           = /usr/local/angstrom/arm/bin
USERSPACE_VAR_PATH  = /home/parav/beaglebone/meanbot/Energia/hardware/userspace/variants/beaglebone

include ../../arduino-mk/Arduino.mk
